### PR TITLE
fix: complement missing trait in 9.5

### PR DESCRIPTION
**Pull request by iLoveTangY**
Missing AgeWidget in chapter 9.5

### CODE REVIEW

**Comment by sunface** [comment]
Great!  

Howerver, due to our exercises are written in both Chinese and English, so besides udpating the chinese exercise you should also modify the english one :)

**Comment by iLoveTangY** [comment]
> Only the Chinese version has this problem...

**Comment by iLoveTangY** [comment]
> Great!
> 
> Howerver, due to our exercises are written in both Chinese and English, so besides udpating the chinese exercise you should also modify the english one :)

Only the Chinese version has this problem...

**Review by sunface — APPROVED** [review]
thank you very much :)

**Pull request merged**
